export const exercisesData = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0001.gif",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
  },

  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0002.gif",
    id: "0002",
    name: "45° side bend",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3214.gif",
    id: "3214",
    name: "arms apart circular toe touch (male)",
    target: "glutes",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0011.gif",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0017.gif",
    id: "0017",
    name: "assisted pull-up",
    target: "lats",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0013.gif",
    id: "0013",
    name: "assisted lying leg raise with throw down",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0020.gif",
    id: "0020",
    name: "balance board",
    target: "quads",
  },
  {
    bodyPart: "lower arms",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0994.gif",
    id: "0994",
    name: "band reverse wrist curl",
    target: "forearms",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1010.gif",
    id: "1010",
    name: "band straight leg deadlift",
    target: "spine",
  },
];
